image: registry.sensetime.com/label-bee/docker-node:14

variables:
  REGISTRY_URL: registry.sensetime.com

stages:
  - lint
  - build
  - deploy

before_script:
  - TAG=$CI_COMMIT_REF_NAME-${CI_COMMIT_SHA:0:8}
  - IMAGE_REGISTRY_URL=$REGISTRY_URL/label-bee/demo:$TAG

.install: &install
  - npm install
  - npm run bootstrap:ci

lint:
  stage: lint
  script:
    - *install
    - npm run build
    - npm run lint

build-demo:
  stage: build
  only:
    - dev
  script:
    - cd ./packages/lb-demo
    - npm install
    - npm run build
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_TOKEN $REGISTRY_URL
    - docker build -t $IMAGE_REGISTRY_URL .
    - docker push $IMAGE_REGISTRY_URL

deploy-demo:
  stage: deploy
  only:
    - dev
  image:
    name: registry.sensetime.com/label-bee/lachlanevenson/k8s-kubectl:latest
    entrypoint: ["/bin/sh", "-c"]
  script:
    - echo -n $KUBE_CONFIG_BJ_IDC_URP | base64 -d > ./kube.conf
    - 'echo "Updating: $TAG"'
    - >
      kubectl patch --kubeconfig ./kube.conf deployment bee-sdk-demo -n sensebee-test -p "{\"spec\":{\"template\":{\"spec\":{\"containers\":[{\"name\":\"bee-sdk-demo\",\"image\":\"$IMAGE_REGISTRY_URL\"}]}}}}"

deploy-dev:
  stage: deploy
  only:
    - dev
  script:
    - npm config set registry https://npm-registry.sensetime.com/
    - echo "//https://npm-registry.sensetime.com/:_authToken=$NPM_TOKEN" > .npmrc
    - *install
    - npm run build
    - npx lerna publish -y --canary --preid \"beta.$(git rev-parse --short HEAD)\" --pre-dist-tag=beta

deploy-build:
  stage: deploy
  only:
    - master
  script:
    - npm config set registry https://npm-registry.sensetime.com/
    - echo "//https://npm-registry.sensetime.com/:_authToken=$NPM_TOKEN" > .npmrc
    - *install
    - npm run build
    - npx lerna version --conventional-graduate --yes
    - npx lerna publish from-package --yes
