image: registry.sensetime.com/fdc/docker-node:20190712

variables:
  REGISTRY_URL: registry.sensetime.com

stages:
  - eslint
  - build
  - deploy

.install: &install
  - npm config set registry https://registry.npm.taobao.org && npm config set sass-binary-site https://npm.taobao.org/mirrors/node-sass
  - npm install -timeout=1000000
  - npm run bootstrap

eslint:
  stage: eslint
  script:
    - *install
    - npm run lint

deploy-dev:
  stage: deploy
  only:
    - dev
  script:
    - *install
    - npx lerna publish from-package --legacy-auth $TNPM_USERPASSWORD_BASE64 --yes

deploy-build:
  stage: deploy
  only:
    - master
  script:
    - *install
    - npx lerna version --conventional-graduate --yes
